version: "3.8"
name: nova-template
services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - "26110:3000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:password@postgresql:5432/nova-template
      - NEXTAUTH_SECRET=kladjsfnsfgposadjmfglökjnsdfkljgjnsdlkfjgnklsdjfnglknkjl
      - NEXTAUTH_URL=http://10.0.10.110:26110
      - JWT_SECRET=dev-secret-change-in-production
    command: npm run dev
    restart: unless-stopped
    networks:
      - postgresql

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "26111:3001"
    volumes:
      - ./dashboard:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://10.0.10.110:26110
    command: npm run dev
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data_dev:
networks:
  postgresql:
    external: true
